name    'yguenane-authconfig'
version '0.1.0'
source 'https://github.com/Spredzy/puppet-authconfig'
author 'Yanis Guenane'
license 'Apache License, Version 2.0'
summary 'A Puppet module that installs and configure authconfig on EL distributions'
description 'This Puppet module allows you to configure Network Authentication Access via authconfig'
project_page 'https://github.com/Spredzy/puppet-authconfig'

dependency 'puppetlabs/stdlib', '3.2.1'
